### PR TITLE
Add DYNACONF_USER_PROVIDER__rbac_enabled support

### PR DESCRIPTION
**Pull request by skarekrow**
This is needed for export-service konflux tests

### CODE REVIEW

**Comment by skarekrow** [comment]
Wrong repo, whoops

**Comment by skarekrow** [comment]
actually, this seems correct for konflux, reopening

**Comment by dscervantes** [comment]
@gbenhaim @ernesgonzalez33

**Comment by ergonzal22** [comment]
@skarekrow if you want this to be able to be passed as a parameter to the pipeline, you will need to add it here: https://github.com/RedHatInsights/bonfire-tekton/blob/main/pipelines/basic.yaml as well

**Comment by dehort** [comment]
`I'm` wondering if we should make this more generic.  Right now (for export-service), we only need to pass `DYNACONF_USER_PROVIDER__rbac_enabled=true`.   However, what if we need another env var in the future??  

From bonfire help:
```
 --env-var TEXT                Define a custom env var to set on the IQE pod
                                in the format of ENV_VAR_NAME=value (can be
                                specified multiple times)
```

Maybe we need to add an `IQE_ENV_VAR` variable that contains a list of environment variables (env_var_1=fred env_var_2=barney) and then split that string on the space so that we can add a `--env-var` to the command for each of the env vars?  In other words:

```
- name: IQE_ENV_VAR
  value: 'env_var_1=fred env_var_2=barney'
```

would turn into:

```
--env-var env_var_1=fred
--env-var env_var_2=barney
```

I think we'd then need to add this to the app specific configuration in the tenant-config github repo and the bonfire-tekton github repo so that its passed all the way down.

This seems kinda gross, but it feels like its going to be needed.  :thinking: 

Is there a better way to do this?

**Comment by ergonzal22** [comment]
@dehort I think that could be solved with an array type parameter: https://tekton.dev/docs/pipelines/tasks/#array-type

**Pull request closed without merging**
